name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:


  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build AlexCalc static HTML via docker
      run: |
        docker build \
        --build-arg ALEXCALC_BUILD_TYPE_LABEL=github-pages \
        -t alexcalc_html \
        -f Dockerfile \
        --target=export_output  \
        --output=./public \
        .

    - name: Deploy built HTML to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        destination_dir: docs
